MODULE GWFUPWMODULE
   !                                                  
   DOUBLE PRECISION, PARAMETER:: HEPS = 1.0E-7                      
   DOUBLE PRECISION, PARAMETER:: CLOSEZERO = 1.0E-15
   DOUBLE PRECISION, PARAMETER:: BIG = 1.0D20 
   DOUBLE PRECISION, PARAMETER:: SMALL = 1.0D-5   
   !
   DOUBLE PRECISION, SAVE, DIMENSION(:), POINTER, CONTIGUOUS :: Sn, So
   !
   LOGICAL, SAVE, POINTER:: LPF_STORAGE        
   ! Cell property data
   INTEGER, SAVE, POINTER:: IUPWCB,IWDFLG,IWETIT,IHDWET,IPHDRY
   INTEGER, SAVE, POINTER:: ISFAC,ICONCV,ITHFLG,NOCVCO,NOVFC
   REAL,    SAVE, POINTER:: WETFCT
   INTEGER, SAVE, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYTYPUPW
   INTEGER, SAVE, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYAVG
   REAL,    SAVE, POINTER, DIMENSION(:),     CONTIGUOUS:: CHANI
   INTEGER, SAVE, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYVKAUPW
   INTEGER, SAVE, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYWET
   INTEGER, SAVE, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYSTRT
   INTEGER, SAVE, POINTER, DIMENSION(:,:),   CONTIGUOUS:: LAYFLG
   INTEGER, SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: IBOUND2
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: VKAUPW
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: VKCB
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: SC1
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: SC2UPW
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: HANI
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: WETDRY
   REAL,    SAVE, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: HKUPW
   !
   TYPE GWFUPWTYPE 
      DOUBLE PRECISION, DIMENSION(:), POINTER, CONTIGUOUS :: Sn, So
      !
      LOGICAL, POINTER :: LPF_STORAGE        
      ! Cell property data
      INTEGER, POINTER:: IUPWCB,IWDFLG,IWETIT,IHDWET,IPHDRY
      INTEGER, POINTER:: ISFAC,ICONCV,ITHFLG,NOCVCO,NOVFC
      REAL,    POINTER:: WETFCT
      INTEGER, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYTYPUPW
      INTEGER, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYAVG
      REAL,    POINTER, DIMENSION(:),     CONTIGUOUS:: CHANI
      INTEGER, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYVKAUPW
      INTEGER, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYWET
      INTEGER, POINTER, DIMENSION(:),     CONTIGUOUS:: LAYSTRT
      INTEGER, POINTER, DIMENSION(:,:),   CONTIGUOUS:: LAYFLG
      INTEGER, POINTER, DIMENSION(:,:,:), CONTIGUOUS:: IBOUND2
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: VKAUPW
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: VKCB
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: SC1
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: SC2UPW
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: HANI
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: WETDRY
      REAL,    POINTER, DIMENSION(:,:,:), CONTIGUOUS:: HKUPW
   END TYPE GWFUPWTYPE                                               
   !
   TYPE (GWFUPWTYPE), DIMENSION(10), SAVE:: GWFUPWDAT
END MODULE GWFUPWMODULE
